import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Card, Divider } from "antd";
import { decodeCookie } from "@/utilities/decoder";

export default function About(props) {
  const router = useRouter();
  const handleLogout = async () => {
    await axios.post("/api/logout");
    router.replace("/login");
  };
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{ marginTop: "1%", display: "flex", justifyContent: "center" }}
      >
        <Card style={{ width: "35%" }}>
          <div style={{ fontSize: "10px" }}>
            Cookies Value : {props?.cookies}
          </div>

          <Divider />

          <center>
            <h1>About</h1>
          </center>

          <div style={{ textAlign: "justify" }}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
            viverra vulputate blandit. Proin nec ipsum imperdiet, commodo velit
            vehicula, porttitor turpis. Class aptent taciti sociosqu ad litora
            torquent per conubia nostra, per inceptos himenaeos. Sed sed diam
            viverra, condimentum purus nec, mollis elit. Curabitur ut velit eu
            leo egestas porta non eu risus. Nunc tempor purus a cursus viverra.
            Maecenas interdum mi sit amet eros maximus, at gravida leo
            tincidunt. Phasellus pulvinar faucibus diam vel dignissim. Curabitur
            convallis dignissim sagittis. Suspendisse potenti. Phasellus justo
            nulla, ullamcorper nec massa vitae, pellentesque aliquet odio. Fusce
            et luctus lacus, quis rutrum neque. Nullam nec efficitur neque. Cras
            tempor convallis purus, et pretium quam pulvinar non. Vivamus mollis
            id nunc sed iaculis. Pellentesque et laoreet dui. Nunc accumsan
            tristique finibus. Quisque laoreet, massa a feugiat sollicitudin,
            turpis purus viverra metus, eu dictum erat augue eget mauris. Nullam
            condimentum risus urna, in rutrum nibh porta in. Etiam sed magna
            lectus. Donec nisl ipsum, tristique at lacus et, porta elementum
            velit. Sed malesuada neque quam, lacinia elementum est iaculis nec.
            Nulla ac pulvinar leo, sit amet sollicitudin tortor. Praesent tempor
            nunc lacus, et lacinia odio aliquam non. Aenean quis consequat
            magna, in cursus eros. Donec elementum mi ex, laoreet viverra lorem
            tempor sed. Praesent commodo nec urna a luctus. Interdum et
            malesuada fames ac ante ipsum primis in faucibus. Curabitur rhoncus
            pulvinar nisl, et finibus ex vehicula eu. Cras a elit orci. In
            ullamcorper convallis velit eget posuere. Nam vitae felis neque.
            Praesent congue ligula et odio molestie commodo. Nunc egestas
            lacinia mi. Integer eu consequat tellus, pharetra fringilla neque.
            Duis molestie, arcu vel lacinia efficitur, leo mi aliquam purus, et
            scelerisque urna nibh vel sapien. Morbi feugiat tempus diam, id
            egestas eros rhoncus non. Class aptent taciti sociosqu ad litora
            torquent per conubia nostra, per inceptos himenaeos. Aliquam mollis,
            nunc et commodo luctus, enim ante mollis tellus, sed euismod sapien
            odio vel nulla. Aliquam posuere metus nec ante pulvinar sodales.
            Nullam malesuada augue risus, ac sollicitudin nisl efficitur vel.
            Maecenas leo enim, bibendum eget tempus sed, feugiat ac nulla.
            Vivamus vel mauris lacinia, fringilla tortor et, pulvinar elit.
            Fusce sit amet consequat purus. Cras condimentum, nibh eget
            hendrerit lobortis, eros diam faucibus nisi, sit amet ornare diam
            mauris quis felis. Nunc sit amet magna blandit, accumsan eros ac,
            egestas tortor. Vivamus aliquam tellus quam, ut laoreet odio
            hendrerit et. In tincidunt sem eu quam mollis, vitae sodales odio
            lobortis. Nullam nec augue eu dui viverra ultricies ac vel dui. Ut
            laoreet leo blandit metus blandit, a vulputate sapien elementum.
            Aliquam erat volutpat. Vestibulum fringilla turpis aliquet,
            fermentum turpis rhoncus, fermentum augue. Duis venenatis ex et
            ultricies fermentum. Sed viverra cursus magna, nec pulvinar nunc
            volutpat ac. Interdum et malesuada fames ac ante ipsum primis in
            faucibus. Pellentesque at fermentum libero, vitae pretium ex. Sed
            euismod tellus commodo, sagittis justo in, iaculis tortor.
            Pellentesque in tellus tellus.
          </div>

          <Divider />

          <Button type="primary" onClick={() => router.push("/profile")} block>
            Profile
          </Button>

          <div style={{ height: "24px" }} />

          <Button type="default" onClick={handleLogout} block>
            Logout
          </Button>
        </Card>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const cookies = decodeCookie(context.req.cookies["cookies-n-nm"]);
  return {
    props: {
      cookies: cookies,
    },
  };
}
