import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Button, Card, Checkbox, Form, Input, notification } from "antd";
import WheatIcon from "../../public/wheat-icon.svg";
import Icon from "@ant-design/icons";

export default function Login() {
  const router = useRouter();
  const { from } = router.query;
  const [loading, setLoading] = useState(false);

  const onFinish = async (values) => {
    try {
      setLoading(true);
      await axios.post("/api/login", {
        username: values.username,
        password: values.password,
        remember: values.remember,
      });
      router.push(from ?? "/about");
      notification.success({
        message: "Success",
        description: "Login succeed",
      });
    } catch (error) {
      notification.error({
        message: "Error",
        description: error?.response?.data?.error,
      });
    } finally {
      setLoading(false);
    }
  };
  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };

  useEffect(() => {
    if (from) {
      notification.error({
        message: "Error",
        description: `Login first to see ${from} page`,
      });
    }
  }, [from]);

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{ marginTop: "7%", display: "flex", justifyContent: "center" }}
      >
        <Card style={{ width: "35%" }}>
          <center>
            <Icon
              component={WheatIcon}
              style={{ fontSize: "240px", marginBottom: "50px" }}
            />
          </center>
          <Form
            name="basic"
            initialValues={{
              remember: true,
              username: "eve.holt@reqres.in",
              password: "cityslicka",
            }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Form.Item
              name="username"
              rules={[
                {
                  required: true,
                  message: "Please input your username!",
                },
              ]}
            >
              <Input placeholder="Username" />
            </Form.Item>

            <Form.Item
              name="password"
              rules={[
                {
                  required: true,
                  message: "Please input your password!",
                },
              ]}
            >
              <Input.Password placeholder="Password" />
            </Form.Item>

            <Form.Item name="remember" valuePropName="checked">
              <Checkbox>Remember me</Checkbox>
            </Form.Item>

            <Form.Item>
              <Button loading={loading} type="primary" htmlType="submit" block>
                Login
              </Button>
            </Form.Item>

            <Button
              type="default"
              onClick={() => router.push("/register")}
              block
            >
              Register
            </Button>
          </Form>
        </Card>
      </div>
    </>
  );
}
