import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { Avatar, Button, Card, Divider } from "antd";
import { decodeCookie } from "@/utilities/decoder";

export default function Profile(props) {
  const router = useRouter();
  const handleLogout = async () => {
    await axios.post("/api/logout");
    router.replace("/login");
  };
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{ marginTop: "1%", display: "flex", justifyContent: "center" }}
      >
        <Card style={{ width: "35%" }}>
          <div style={{ fontSize: "10px" }}>
            Cookies Value : {props?.cookies}
          </div>

          <Divider />

          <center>
            <h1>Profile</h1>
            <div style={{ height: "20px" }} />
            <Avatar
              shape="square"
              size={64}
              src="https://img.tek.id/img/content/2022/07/05/52601/minions-the-rise-of-gru-raup-penghasilan-film-animasi-tertinggi-selama-pandemi-TjA7HSMLR6.jpg"
            />
            <div style={{ height: "20px" }} />
            <div>Lorem ipsum dolor sit amet</div>
          </center>

          <Divider />

          <Button type="primary" onClick={() => router.push("/about")} block>
            About
          </Button>

          <div style={{ height: "24px" }} />

          <Button type="default" onClick={handleLogout} block>
            Logout
          </Button>
        </Card>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const cookies = decodeCookie(context.req.cookies["cookies-n-nm"]);
  return {
    props: {
      cookies: cookies,
    },
  };
}
