import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Card, Form } from "antd";
import WheatIcon from "../../public/wheat-icon.svg";
import Icon from "@ant-design/icons";

export default function Register() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{ marginTop: "7%", display: "flex", justifyContent: "center" }}
      >
        <Card style={{ width: "35%" }}>
          <center>
            <Icon
              component={WheatIcon}
              style={{ fontSize: "240px", marginBottom: "50px" }}
            />
          </center>
          <Form
            name="basic"
            initialValues={{
              remember: true,
              username: "eve.holt@reqres.in",
              password: "cityslicka",
            }}
            // onFinish={onFinish}
            // onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <center style={{ marginBottom: "50px" }}>
              <h1>REGISTER FORM</h1>
            </center>

            <Form.Item>
              <Button type="primary" htmlType="submit" block>
                Register
              </Button>
            </Form.Item>

            <Button type="default" onClick={() => router.push("/login")} block>
              Login
            </Button>
          </Form>
        </Card>
      </div>
    </>
  );
}
